# Generated by Django 5.1.2 on 2024-10-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instock',
            name='stock',
        ),
    ]
