# Generated by Django 5.1.2 on 2024-10-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_instock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='instock',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.flavor'),
        ),
        migrations.AddField(
            model_name='instock',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
