# Generated by Django 5.1.2 on 2024-10-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_instock_flavor_instock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
